name: CI/CD pipeline for Lambda
on:
  push:
    branches:
      - main

jobs:
  lambda_demo1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  lambda_demo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 
          aws-secret-access-key:
          aws-region: us-east-1
      -  name: Creating deployment zip
         run: |
          sudo apt install zip
          mkdir -p ./deployment_zip 
          pip install snowflake-connector-python --platform manylinux2010_x86_64 --only-binary=:all: -t ./deployment_zip
          cp ./backend/index.js  ./deployment_zip
          cd deployment_zip 
          zip -r lambda_zip.zip *
      - name: lambda_code_update
        run: |
          aws lambda update-function-code --function-name getALLUsers --zip-file fileb://./deployment_zip/lambda_zip.zip